print("""'A Clean Start to a Great Build'
CORSAIR iCUE 4000X RGB - A Clean Start to a Great Build
https://www.youtube.com/watch?v=eiVOjWPkkGg&fbclid=IwAR17crgZy3DNLby8sPNNUjvVpjkxXBRVG_L88xPsyp6bj8TmYroTyNH6GZs
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl..:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:   .cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'    .;xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKNMMMMMMMMMMMMMNl       'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;o0NMMMN0KNWMMMO.        ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, .,o0WWk;,:xXWKc.        .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.   .oNWd,. .ckKKko;.      ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0XWMMMMMWMMMMNc    .xWN0c   .,oKWWXkl'    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,:d0NMMXxxKWWx.    ,KMM0'     .:kXMMNkc.  lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:  .,xNWd..:x00xo:''xWMNl        'o0WMWO;.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.   .xWX:   .:xKWNKXWMMk.         .:kNMXdxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKNMMX:    ,0Wx.     .:xKWMMM0,            ,dKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:,lk0Odlc;;xWK,        .c0WMX;              .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .;oOXNNNWNc          lXNX;                .cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:      .:d0NWo          c0NK,                  .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.        .kWo          :0XO.                    .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.         oNl          c0Xd.                      .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,         oK:          lX0;                        .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,         ok'         .oKo.                         .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.        .ol          'cc.                           oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.        .c'          ..                            .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;         .'                 ..',;:ccllllllc:,..     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.                   .';:lodxOKXNNWMMMMMMMMMMWWN0x:. .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.             ..,coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMWOlOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'        ..,cok0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.    .':lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl..':okKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMXkdkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMWXOxooddddk0NWMMMMWXOxddxdxOXWMMWXkxddxkkkxk0NWMMMMMW0kxddxddkXWMMMMMMW0xONMMMMMMMW0xddxOXWKkxxxxkkxxkKNMMWXKXWMMM
MMMMNk:..;ok00kd;.;OMMWOc''lk00kl,'cONMNd.  :OOkl'.'dNMMW0:'.:k0KOl':KMMMMMWO' .oNMMMMMMW0;  .xNWXl  .lOOkc..;kX0dldKWMM
MMW0:. 'kNMMMMMMXo'dWXl. ,OWMMMMW0; .lXMO.  dWMMWd. .xWMX: .:kMMMMWkdKMMMMM0;   .xWMMMMMMNl  ,0MMWx. .kMMMNl  'OXOkOXWMM
MMK;  'OMMMMMMMMMNk0No. .kWMMMMMMMO.  lNO. .dWMMMk. .dWMK;  .'d0XWMWNWMMMMX:'l;  'OMMMMMMNl  '0MMWx. .OMMMWo  .OMWWWMMMM
MMx.  lNMMMMMMMMMMMM0,  ;KMMMMMMMMX:  'OO. .dNNKk; .lXMMWO,    ..;oONMMMMNl.oNO'  ;KMMMMMNl  '0MMMx. .kWXKx' .dNMMMMMMMM
MWx.  lWMMMMMMMMMMMM0'  ;KMMMMMMMMX:  .OO. .dXd'..:OWMMMMMNkdl,.    ;0WMWx.;kK0l.  cXMMMMNl  '0MMMx. .kXl...c0WMMMMMMMMM
MM0,  ,0MMMMMMMMMNO0Nl  .kWMMMMMMMO'  cXO. .dWXl. .lXMMMNXWMMMWKx:.  cNWk''loooo;. .oNMMMNl  '0MMWx. .kMK:  .xNMMMMMMMMM
MMWO,  ;OWMMMMMMNd,dWKc  ;0MMMMMMK:  :KMO. .dWMNd.  cKMMOckWMMMMMK;  oN0;,OWMMMMXc  .xWMMNl  ,0MMMx. .OMMXc. .oNMMMMMMMM
MMMWXd,..cx0XX0x:.'kMMNk;.'o0XX0d,.;xNMWx.  lXMMWk'  ,OW0,.cdkKK0o..lK0:.lNMMMMMWk.  'kNWK:  .kWWNl  .dNMMNo. .cKMMMMMMM
MMMMMMN0xolodddodOKWMMMMW0xoodddox0NMMWXkooox0WMMWKo,.'o00xoloodooxKWNOdokXWMMMMNOooooxKN0doookXWKxoooxXWMMWOc'.,xXMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kkXWMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""")